[config]
schemaVersion = "0.0.1"

[package]
namespace = "JevMods"
name = "JevIntroSkip"
versionNumber = "1.0.6"
description = "Skips the studio logos, the intro video, the lore text and the Valkyrie flight, so you get into the game without the wait. Each one is a toggle, so you only skip what you want to."
websiteUrl = "https://github.com/JevMods/JevIntroSkip"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2351"

[build]
icon = "./package/icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./src/JevIntroSkip/bin/Release/JevIntroSkip.dll"
target = "/"

[[build.copy]]
source = "./package/CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]

[publish.categories]
valheim = [ "mods", "tweaks", "client-side" ]
